-- ============================================================
-- ⚠️  ESTE ARQUIVO FOI SUBSTITUÍDO PELA PASTA  migrations/
-- ============================================================
--
-- As migrações agora são versionadas. Veja migrations/README.md.
--
-- Como aplicar:
--   1. Supabase Dashboard → SQL Editor
--   2. Rode migrations/000_controle.sql (uma vez)
--   3. Consulte o que já foi aplicado:
--        SELECT * FROM "_MIGRATIONS" ORDER BY version;
--   4. Rode em ordem os arquivos que faltarem:
--        001_clientes_produtos.sql
--        002_rh_completo.sql
--        003_permissoes.sql
--        004_venda_transacional.sql
--        005_auditoria.sql
--
-- Se você já rodava este MIGRATIONS.sql antigo, o conteúdo dele
-- equivale às versões 001–004 (todas idempotentes — rodar de novo
-- não causa problema). Registre-as na tabela de controle com:
--
--   INSERT INTO "_MIGRATIONS" (version, name) VALUES
--     ('001','clientes_produtos'), ('002','rh_completo'),
--     ('003','permissoes'), ('004','venda_transacional')
--   ON CONFLICT (version) DO NOTHING;
-- ============================================================
